// COM.idl : IDL source for COM
//

// This file will be processed by the MIDL tool to
// produce the type library (COM.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
    object,
    uuid(c636d6f8-581e-4b4e-bf29-db710673ba6f),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface IDoWork : IDispatch
{
    HRESULT Initialize();
    HRESULT Test();
    HRESULT SendEvent([in] IDispatch *pIEvent);
};
[
    object,
    uuid(26966f2b-a975-4a4b-9855-7e93dfb6815c),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface IEventData : IDispatch
{
    [propget, helpstring("property Key")] HRESULT Key([out, retval]long *pVal);
    [propput, helpstring("property Key")] HRESULT Key([in] long val);
};
[
    object,
    uuid(94183CED-A9FC-4E26-8358-45408FBF2115),
    dual,
    nonextensible,
    pointer_default(unique)
]
interface IProcessingPlugins : IDispatch
{
    HRESULT Initialize(IDispatch *piDoWork);
    HRESULT ProcessFlaw();
};
[
	uuid(84e7e34c-32cb-4363-825b-5d05631636f9),
	version(1.0),
]
library COMLib
{
	importlib("stdole2.tlb");
    [
        uuid(d4c945f1-3aa2-4acb-9ee7-a92c3be889af)
    ]
    coclass DoWork
    {
        [default] interface IDoWork;
    };
    [
        uuid(28e09e60-4236-459f-bb6a-84d5b1dd996b)
    ]
    coclass EventData
    {
        [default] interface IEventData;
    };
    [
        uuid(3A7F93DF-2A3B-496A-B148-A1838578A961)
    ]
    coclass ProcessingPlugins
    {
        [default] interface IProcessingPlugins;
    };
};

